
name: update-calendar
run-name: Updating the calendar
on:
  schedule:
    - cron:  '30 1 * * *'
jobs:
  update-calendar:
    runs-on: ubuntu-latest
    steps:
      - run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_MOvsiHYSohgh2uoGcYvsQyz8687S/GpjKffDXy8
